sfstoolbox/sfs-python

sfs/mono/drivingfunction.py
sfs/mono/source.py
sfs/time/drivingfunction.py
sfs/util.py

This tries to fix #20 and #28.
I renamed `util.normal_vector()` to `util.normalize_vector()` as proposed in #28 and used it for every single dimensional direction vector `n`. The field plotted in #20 looks now correct with this.
I'm still not happy with the naming, which I will discuss directly in #28 and there is the problem how to handle several unit vectors at once like `n0 = util.asarray_of_rows(n0)`.

Fix non-unit direction vectors

---

examples/time_domain.py
sfs/defs.py
sfs/time/drivingfunction.py
sfs/time/soundfield.py
sfs/time/source.py
sfs/util.py

For now, this is just a proof of concept.
Alternatives are very welcome.
And suggestions for improvements, too.
For now, there are no doc changes yet. I'll do that if we decide to go that way ...

Add signal class and helper function

---

examples/time_domain.py
sfs/time/drivingfunction.py

This implements the simulation of a virtual focused sound source for time based 2.5D-WFS.
- The documentation is updated accordingly.
- There is also an example.

Add time based 2.5D-WFS focused source 

---

doc/index.rst
doc/references.rst
sfs/mono/drivingfunction.py
sfs/mono/source.py

At the moment we handle citations of references a little bit sloppy. They are usually in the form of `[Spors et al, 2008]` without explaining which exact paper this is.
I see two solutions to this:
1.) As implemented in this pull request: stay with the short citations in the help messages, but make them click able and add a reference page in the online documentation. The above statement would then be `[Spors2008]_` in the help text of the function.
2.) Another solution would be to add the name of the actual publication to the help text as done in #45 at the moment.

Handling of references

---

sfs/mono/source.py

The argument `N` can now handle scalars or a vector containing for all three dimensions `None` for computation of max order, a scalar for a given maximum order or a vector for given orders per dimension. For instance
- `N=10 or N = [10, 10, 10]` computes the field in all three dimensions up to order 10
- `N = [None, None, [0]]` calculates the order in the first two dimensions and uses zeroth-order for the third dimension

Generalization of the modal order argument

---

sfs/mono/drivingfunction.py
sfs/util.py

This tries to fix #43.
Unfortunately, the return values of the spherical Bessel functions seem to have changed as well, even if the documentation still states `ndarray`.
If you execute the following code with my changes you will get an error:
```python
import numpy as np
import sfs
nk = 0, -1, 0  # direction of plane wave
omega = 2 * np.pi * 1000  # frequency
R0 = 1.5  # radius of secondary sources
x0, n0, a0 = sfs.array.circular(200, R0)
grid = sfs.util.xyz_grid([-1.75, 1.75], [-1.75, 1.75], 0, spacing=0.02)
d = sfs.mono.drivingfunction.nfchoa_25d_plane(omega, x0, R0, nk)
```
The error is
```
IndexError                                Traceback (most recent call last)
<ipython-input-5-5d956e53e92e> in <module>()
----> 1 d = sfs.mono.drivingfunction.nfchoa_25d_plane(omega, x0, R0, nk) …
```

Switch to spherical_jn and spherical_yn

---

doc/conf.py
doc/readthedocs-environment.yml
doc/references.bib
doc/references.rst
doc/requirements.txt
sfs/mono/drivingfunction.py
sfs/mono/source.py
sfs/util.py

As proposed in #49 I switched to [sphinxcontrib-bibtex](https://github.com/mcmtroffaes/sphinxcontrib-bibtex/) for references.
Using the `unsrt` style this creates a numbered ([1], [2], ...) list of references, see http://python.sfstoolbox.org/en/bibtex/references.html.
This means inside the text we have now also only numbered links like "Eq.(17) from [[7]](http://python.sfstoolbox.org/en/bibtex/references.html#spors2008)", see [wfs_2d_plane](http://python.sfstoolbox.org/en/bibtex/frequency-domain.html#sfs.mono.drivingfunction.wfs_2d_plane). In most of the times this should be fine, I only changed it for the first entry in the [docstring of image_sources_for_box](http://python.sfstoolbox.org/en/bibtex/utilities.html#sfs.util.image_sources_for_box).
In a third commit I also started to clean …

Use sphinxcontrib-bibtex for references

---

doc/_static/css/title.css
doc/_template/layout.html
doc/conf.py

To make it more obvious that we three different sub-projects under SFS Toolbox I created a small navigation on the right side. You can preview it at http://python.sfstoolbox.org/en/nav/
A few remarks:
1) The last commit has to be deleted before merging
2) The related pull requests https://github.com/sfstoolbox/theory/pull/25 and https://github.com/sfstoolbox/sfs-matlab/pull/180 have to be merged as well
3) For the matlab and python version we also have to make an official release as the default url points to their last stable release

DOC: add link to theory, matlab, and python to sidebar

---

sfs/plot.py

closes #50 
(This may become obsolete in matplotlib 2.2 or not.
Since it's easy enough, I propose to fix it now anyway.)

Clip soundfield into float64 range for plotting

---

sfs/mono/drivingfunction.py

Plane Wave WFS 2.5D driving function corrected in terms of amplitude:
-amplitude factor sqrt(8pi)
-corrected handling of norm(xref-x0)
Plane Wave NFC HOA 2.5 D driving function corrected in terms of phase:
-phase term is correct in the LaTex comment, but was erroneously coded

Correct driving functions

---

CONTRIBUTING.rst

I guess we didn't updated the link when we renamed the project to sfs-python.

Fixed link to read the docs build page

---

sfs/mono/drivingfunction.py

This replaces the ASCII math notations for the monochromatic driving functions.

DOC: math notations for mono driving functions

---

doc/conf.py
doc/math-definitions.rst

Yet another alternative for #80, #81 and #82.

DOC: Make LaTeX math definitions LaTeX compatible

---

sfs/plot.py

Before
After
These plots are generated by
sfs-python/doc/examples/sound_field_synthesis.py
with 
```python
grid = sfs.util.xyz_grid([-2, 2], [-2, 2], 0, spacing=0.5)
```

Adjust axis limits in sound field plots

---

doc/examples/horizontal_plane_arrays.py
doc/examples/sound_field_synthesis.py
doc/examples/time_domain.py
sfs/mono/drivingfunction.py
sfs/mono/soundfigure.py
sfs/time/drivingfunction.py
sfs/util.py

They are not specific to monochromatic applications, as @chris-hld already mentioned in https://github.com/sfstoolbox/sfs-python/issues/25#issuecomment-266313599.
I didn't know any better place than `sfs.util`, but if somebody else does, please speak up!

Move source selection helpers to sfs.util

---

sfs/util.py
tests/test_util.py

This PR contains three minor updates to the conversion of Cartesian to spherical coordinates and vice versa.
- Reflect the actual range of 'alpha' in the doc-string
- Rename 'Elevation' to 'Colatitude' in the doc-string 
- Update the test to pre-calculated values
Discussion in https://github.com/sfstoolbox/sfs-python/issues/59.

Cart2sph update

---

doc/examples/time_domain_nfchoa.py
sfs/mono/drivingfunction.py
sfs/time/drivingfunction.py
sfs/time/source.py
sfs/util.py

NFC-HOA driving functions are implemented using first/second-order section filters.
* based on [Spors et al](http://www.int.uni-rostock.de/fileadmin/user_upload/publications/spors/2011/Spors_etal_WASPAA_2011_efficient_NFCHOA.pdf) and [Hahn and Spors](http://www.aes.org/e-lib/browse.cfm?elib=18609)
* driving functions for plane wave and point source
To be discussed
```
sos = {}
for m in range(0, max_order+1):
...
sos[m] = sig.zpk2sos(z0, zinf, k, pairing='nearest')
```

NFC-HOA second-order-section filters

---

.travis.yml
doc/examples.rst
doc/examples/animations-pulsating-sphere.ipynb
doc/examples/animations_pulsating_sphere.py
sfs/mono/source.py
sfs/plot.py

Simulation of the particle displacement and particle velocity of a pulsating sphere.

Pulsating sphere

---

sfs/util.py

Unescaped underscores seem to work with MathJax, but LaTeX itself does complain.

DOC: Escape underscore in \text{}

---

sfs/plot.py

I still don't know what's the best way to extend the array example plots in a way to show all the numbers, but I'm quite sure we should clip the numbers to the axes.
If we don't do that, numbers might end up very far outside the plot if we only show a section of the array.

Clip loudspeaker numbers

---

CONTRIBUTING.rst
doc/conf.py
sfs/util.py

Broken/outdated links can be found with
python3 setup.py build_sphinx -b linkcheck
I did *not* update the SFS-Toolbox equation links, because those are still in flux, see #103.

DOC: Update a few URIs

---

sfs/util.py

It turns out that #110 fixed the LaTeX output, but it broke the MathJax output.
This PR should work for both.
If you don't like this, we could also use something like `M` or `M_\text{max}` as symbol for the maximum order.
Any preferences?

DOC: use \mathtt{} for "max_order"

---

CONTRIBUTING.rst

This closes #87 by adding explanations how to build the EPUB and PDF files locally.

Add intro how to build PDF and EBUP documentations

---

doc/references.bib
sfs/mono/wfs.py

I remember we had this discussion a while ago in the Matlab toolbox. I try it here again :-)
I'd vote to change our default WFS 2.5D point source to that driving function originating from Delft, which is compatible with the recent works of Firtha, i.e. the [unified WFS framework](https://github.com/gfirtha/gfirtha_phd_thesis).
Our currently used version is -- due to the further approximation -- not easy to handle in terms of
- consistent and proper amplitude normalization
- introducing/defining other referencing schemes
The PR is merge prepared in terms of our latest changes w.r.t. driving function and docstring example handling, but not for literature references.
I would not mind to supply both driving functions with a consistent and proper name scheme. I did not come up with a …

WFS 2.5D point source

---

doc/examples/horizontal_plane_arrays.py
doc/examples/mirror-image-source-model.ipynb
doc/examples/sound_field_synthesis.py
doc/examples/time_domain.py
sfs/array.py
sfs/fd/__init__.py
sfs/fd/esa.py
sfs/fd/nfchoa.py
sfs/fd/sdm.py
sfs/fd/source.py
sfs/fd/wfs.py
sfs/plot2d.py
sfs/plot3d.py
sfs/tapering.py
sfs/util.py

Keyword-only arguments are a nice Python 3 feature to force the user to use keyword arguments, avoiding very long sequences of positional parameters.
The good thing is that if it gets annoying, the requirements can be weakened without causing backwards-compatibility issues.
Adding them is typically backwards-incompatible.

Keyword-only arguments everywhere

---

doc/conf.py
sfs/fd/nfchoa.py
sfs/td/wfs.py

This updates the already existing URL references to the theory page to use the new `https://sfs.rtfd.io` address and the new naming scheme of equation labels.
NOTE: version 3.2 of the documentation is not online yet as it requires sfs 0.5.0 to be released first.
I tested the new links by changing `3.2` to `test-rtfd` in `conf.py` which is a version of the documentation build against the current sfs master. I did the test with `python3 setup.py build_sphinx -b linkcheck`.

DOC: Update existing links to theory

---

doc/math-definitions.rst

TBH, I don't understand what the difference is between the two, but if I use `\operatorname`, I get an "ffi ligature" instead of a "lowercase greek letter delta" in the PDF.

Use \mathop instead of \operatorname

---

sfs/fd/source.py
sfs/td/source.py

This suppresses the warnings mentioned in #107.
But I think the current solution is very ugly and covers only a few of the places where this can occur.
The problem is that a lot of our sources, e.g. a point source have some points where they are not defined and it is valid to have `NaN`, `Inf`, divide by zero or other stuff. But it will be a huge effort to find every line where this has to be fixed.
Another solution would be to generally allow for division by zero or multiplication by `NaN` in the whole toolbox, but this is also not nice.
Has somebody an idea how to better handle undefined points in numpy?

Hide warnings for a few undefined points

---

sfs/plot2d.py

Some color maps seem to use a `tuple` of colors instead of a `dict`, this change allows both.

Extend _register_cmap_clip()

---

doc/conf.py

Former has been deprecated and it stopped working in Sphinx's master
branch: https://github.com/sphinx-doc/sphinx/issues/6930

DOC: autodoc_default_flags -> autodoc_default_options

---

sfs/fd/__init__.py
sfs/td/__init__.py

The docstrings for `synthesize()` appear to suggest a wrong signature for `secondary_source_function()`. Modified this to a more reasonable signature. I hopefully have not overseen anything.

doc string modification

---

doc/conf.py
doc/references.rst
doc/requirements.txt
sfs/util.py

the test in https://github.com/sfstoolbox/sfs-python/pull/168 are failing as `sphinxcontrib-bibtex` introduced a breaing change with version 2.0.0 as you have to add another config setting.
This fixes thie issue.

DOC: add compatibility for sphinxcontrib-bibtex>=2

---

sfs/td/wfs.py

As we introduced a new 2.5D WFS point source driving function in frequency domain with version 0.5.0 we should do this in time frequency as well for consistency, I'd propose.
Thus, for time domain same idea as for frequency domain: putting the new version into `point_25D()` (this is the 3D->2.5D Delft approach) and creating `point_25d_legacy()` that holds the function which was used up to <=0.6.0 (this is the 2D -> 2.5D approach by Rabenstein/Spors).
Furthermore, some minor corrections in the math docstrings for the other time domain WFS functions and some pep8 issues fixed.
I would suggest to create a 0.6.1 minor release to introduce the new feature.

introduce new wfs 2.5D point source time domain driving function

---

doc/conf.py

This updates conf.py to support spinx4 using mathjax2, furthermore obsolet add_stylesheet() is fixed. By this the RTD build should work again.

build doc fix for sphinx4+mathjax2

---

sfs/fd/wfs.py
sfs/td/wfs.py

Follow up #168, since not all critics were handled before merge.
So, how to handle the `..versionchanged::` in the docstring in a meaningful way?

docstring mods wfs.py in td/fd follow up #168

---

doc/conf.py

Apparently, the API of `doc2path()` was changed a long time ago and the old behavior was removed in Sphinx 4 (https://github.com/sphinx-doc/sphinx/pull/7416).
This led to incorrect links at the top of notebooks.

DOC: fix docname in prolog/epilog

---

sfs/plot2d.py

This might come in handy for the plots in the 2.5D WFS examples from #184.

Add plot2d.level_contour()
